server:
  servlet:
    context-path: /api/v1
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${datasource-url}
    username: ${datasource-username}
    password: ${datasource-password}

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        generate_statistics: false
        ddl-auto: update
        jdbc:
          batch_size: 100
        cache:
          use_second_level_cache: false
        logging:
          level:
            org.hibernate.SQL: DEBUG
            org.hibernate.type.descriptor.sql.BasicBinder: TRACE

#    enabled: true
#    encoding: UTF-8
#    baseline-on-migrate: true
#    locations: classpath:db/migration/local

#  cache:
#    type: redis
#    redis:
#      time-to-live: 60000
#      cache-null-values: true
#
#  redis:
#    host: localhost
#    port: 6379

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: src/main/resources/files

# Hibernate
logging:
  level:
    com:
      querydsl: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        BasicBinder: TRACE


#springdoc:
#  version: 1.0
#  packages-to-scan: tuk.mentor
#  swagger-ui:
#    path: /api-docs
#    tags-sorter: alpha
#    operations-sorter: alpha
#  api-docs:
#    path: /api-docs/json
#    groups:
#      enabled: true
#  cache:
#    disabled: true
#  default-produces-media-type: application/json;charset=UTF-8
#  default-consumes-media-type: application/json;charset=UTF-8

cloud:
  aws:
    s3:
      bucket: 2023-tukorea-graduation-mento
    credentials:
      access-key: ${access-key}
      secret-key: ${secret-key}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

app:
  cors:
    # comma (',') seperated list of allowed origins for CORS
    allowed-origins: http://localhost, http://localhost:3000
